#### Task 5-2
The following will find the average daily high and low temperatures for a specified week.

In [1]:
import numpy as np
np.set_printoptions(precision=1)

The following represents our input data.  We'll input it as a Python array, and then convert it to a NumPy array.  When we create the array, we'll use dtype=object to bring in different data types.

In [2]:
data = [[1, 88, 68, 25, 10, 'Sunny', False],
        [2, 84, 65, 31, 5, 'Cloudy', False],
        [3, 86, 66, 32, 5, 'Light Rain', False], 
        [4, 89, 67, 26, 5, 'Rain', False],
        [5, 92, 70, 22, 10, 'Sunny', False],
        [6, 95, 71, 18, 20, 'Sunny', True],
        [7, 94, 69, 27, 10, 'Sunny', False]]

In [3]:
weather_data = np.array(data, dtype=object)
weather_data

array([[1, 88, 68, 25, 10, 'Sunny', False],
       [2, 84, 65, 31, 5, 'Cloudy', False],
       [3, 86, 66, 32, 5, 'Light Rain', False],
       [4, 89, 67, 26, 5, 'Rain', False],
       [5, 92, 70, 22, 10, 'Sunny', False],
       [6, 95, 71, 18, 20, 'Sunny', True],
       [7, 94, 69, 27, 10, 'Sunny', False]], dtype=object)

The following characteristics provide information about our ndarray.

In [4]:
weather_data.ndim, weather_data.shape, weather_data.size, weather_data.strides

(2, (7, 7), 49, (56, 8))

The following will take a slice of just the high and low temperature columns.  Note that the commented out vesion below will work, but creates a new array.  To avoid this, the numpy arr.astype(type, copy=False) approach can be used which creates a view of the data in that specified format.

In [5]:
high_low = np.array(weather_data[:,1:3], dtype=float, copy=False)
# high_low = weather_data[:,1:3].astype(np.float64, copy=False)
high_low

array([[88., 68.],
       [84., 65.],
       [86., 66.],
       [89., 67.],
       [92., 70.],
       [95., 71.],
       [94., 69.]])

Next we'll get the average for each row by specifying axis=1.

In [6]:
daily_avg = high_low.mean(axis=1)
daily_avg

array([78. , 74.5, 76. , 78. , 81. , 83. , 81.5])

Finally we'll calculate the average for the entire week...

In [7]:
weekly_avg = daily_avg.mean()
'{0:.2f}'.format(weekly_avg)

'78.86'